import { api } from "./axios";
import { getSmartPetCareAPI } from "./generated";

export { api, noAuthApi } from "./axios";
export * from "./generated";

export const {
  deleteApiPetsId,
  deleteApiRemindersId,
  deleteApiUsersId,
  getApiAuthOauthGoogle,
  getApiAuthOauthGoogleCallback,
  getApiPets,
  getApiPetsId,
  getApiPetsPetIdHealthRecords,
  postApiPetsPetIdHealthRecords,
  getApiPetsPetIdHealthRecordsRecordId,
  patchApiPetsPetIdHealthRecordsRecordId,
  deleteApiPetsPetIdHealthRecordsRecordId,
  getApiProfileMe,
  getApiReminders,
  getApiRemindersId,
  getApiRemindersIdRuns,
  getApiRemindersPetPetId,
  getApiSessions,
  getApiSessionsSessionId,
  getApiSessionsSessionIdMessages,
  patchApiPetsId,
  patchApiRemindersId,
  patchApiUsers,
  getApiProfileAvatarUserId,
  postApiProfileAvatar,
  postApiAuthConfirmEmail,
  postApiAuthLogin,
  postApiAuthLogout,
  postApiAuthResendConfirmation,
  postApiAuthOauthGoogleMobile,
  postApiAuthRefresh,
  postApiAuthRegister,
  postApiPets,
  postApiReminders,
  postApiRemindersRunsRunIdAcknowledge,
  postApiSessions,
  postApiSessionsSessionIdMessages,
  postApiSessionsSessionIdMessagesMessageIdRetry,
  patchApiPetsIdPhoto,
  deleteApiNotificationsDeviceTokenToken,
  postApiNotificationsDeviceToken,
  getApiSymptoms,
  getApiSymptomsId,
} = getSmartPetCareAPI(api);
